<!--
  ~ Licensed to the Apache Software Foundation (ASF) under one
  ~ or more contributor license agreements. See the NOTICE file
  ~ distributed with this work for additional information
  ~ regarding copyright ownership. The ASF licenses this file
  ~ to you under the Apache License, Version 2.0 (the
  ~ "License"); you may not use this file except in compliance
  ~ with the License. You may obtain a copy of the License at
  ~
  ~ http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing,
  ~ software distributed under the License is distributed on an
  ~ "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ KIND, either express or implied. See the License for the
  ~ specific language governing permissions and limitations
  ~ under the License.
  -->
<table summary="header table" class="FULL_BLANK">
  <tr>
    <td>
	<table summary="header table" width="100%">
	  <tr>
	  	<td>
		<table summary="embedded header table">
  		  <tr>
    		<td align="left"><img src="axis2-web/images/asf-logo.gif" alt="Apache Software Foundation Logo"></td>
    	 	<td align="right"><img src="axis2-web/images/axis_l.jpg" alt="AXIS Logo"></td>
          </tr>
        </table>
		</td>
		<td>
		&nbsp;
		</td>
	  </tr>
	</table>
